name: LargeSparge
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9382195530924946
title: 'Website software that actually brings you business!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#442938'
    - '#aec0c2'
    - '#625965'
    - '#7d7880'
  brandStrength: 0.0625
  lightness: 0.28647146723233163
  saturation: 0.6875
  rhythmicContrast: 0.44381008041091263
purpose: []
